# Generated by Django 4.2.5 on 2023-09-25 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenIDprovider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField()),
                (
                    "provider_info",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StateSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webid", models.URLField(blank=True, default="", null=True)),
                ("state", models.CharField(max_length=255, unique=True)),
                (
                    "redirect_view",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "client_id",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "client_secret",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("DPoP_key", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "code_verifier",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "id_token",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "token_type",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "oicdp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pod_registration.openidprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolidPod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
